[window_params]
title = "Bicycle Kinematic Model"
width = 1080 # pixels
height = 720 # pixels

[chart_params]
background_color = [0, 0, 0]
label_color = [0, 250, 0]
margin = 15
label_size = 30
label_font = "sans-serif"
label_font_size = 15
x_range = [-50.0, 50.0]
y_range = [-50.0, 50.0]
