[package]
name = "rust_robotics"
version = "0.1.0"
authors = ["Samir Hassen"]
edition = "2021"

[dependencies]
minifb = "0.27"
nalgebra = "0.33.0"
plotters = "0.3.3"
plotters-bitmap = "0.3.6"
serde = { version = "1.0.205", features = ["derive"] }
toml = "0.8.19"
