name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test ${{ matrix.target }}
    
    strategy:
      fail-fast: false

      matrix:
        include:
          - { target: x86_64-unknown-linux-gnu, os: ubuntu-latest }
          - { target: x86_64-apple-darwin, os: macos-latest }

    runs-on: ${{ matrix.os }}

    # add more steps, code coverage, benchmarks, etcs
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
