name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test ${{ matrix.target }}
    
    strategy:
      fail-fast: false

      matrix:
        include:
          - { target: x86_64-unknown-linux-gnu, os: ubuntu-latest }
          - { target: x86_64-apple-darwin, os: macos-latest }

    runs-on: ${{ matrix.os }}

    # add more steps, code coverage, benchmarks, etcs
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose

    
  codecov:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: rustup update stable
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Generate code coverage
        run: cargo llvm-cov --all-features --workspace --lcov --ignore-filename-regex bin/ --output-path lcov.info
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          files: lcov.info
          fail_ci_if_error: true

  # Copied from https://github.com/evenfurther/pathfinding. Update if necessary
  # benchmarks:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v4
  #       name: Checkout
  #     - uses: actions/cache@v4
  #       with:
  #         path: |
  #           ~/.cargo/registry
  #           ~/.cargo/git
  #           target
  #         key: ${{ runner.os }}-cargo-stable-${{ hashFiles('Cargo.toml') }}

  #     - uses: actions-rs/toolchain@v1
  #       name: Install Rust toolchain
  #       with:
  #         profile: minimal
  #         toolchain: stable
  #         override: true

  #     - uses: baptiste0928/cargo-install@v3
  #       name: Install cargo-codspeed (with cache)
  #       with:
  #         crate: cargo-codspeed

  #     - uses: actions-rs/cargo@v1
  #       name: Build benchmarks
  #       with:
  #         command: codspeed
  #         args: build

  #     - uses: CodSpeedHQ/action@v3
  #       name: Run benchmarks
  #       with:
  #         run: cargo codspeed run


